#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : blktrace
Version  : 1.1.0
Release  : 10
URL      : http://brick.kernel.dk/snaps/blktrace-1.1.0.tar.gz
Source0  : http://brick.kernel.dk/snaps/blktrace-1.1.0.tar.gz
Summary  : Block IO tracer
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : libaio-dev

%description
btrace can show detailed info about what is happening on a block
device io queue. This is valuable for diagnosing and fixing
performance or application problems relating to block layer io.


Authors:
--------
    Jens Axboe <axboe@kernel.dk>

%prep
%setup -q -n blktrace-1.1.0

%build
make V=1 CFLAGS="%{optflags}" all

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/local/bin/blkiomon
/usr/local/bin/blkparse
/usr/local/bin/blkrawverify
/usr/local/bin/blktrace
/usr/local/bin/bno_plot.py
/usr/local/bin/btrace
/usr/local/bin/btrecord
/usr/local/bin/btreplay
/usr/local/bin/btt
/usr/local/bin/iowatcher
/usr/local/bin/verify_blkparse
/usr/local/man/man1/blkparse.1
/usr/local/man/man1/blkrawverify.1
/usr/local/man/man1/bno_plot.1
/usr/local/man/man1/btt.1
/usr/local/man/man1/verify_blkparse.1
/usr/local/man/man8/blkiomon.8
/usr/local/man/man8/blktrace.8
/usr/local/man/man8/btrace.8
/usr/local/man/man8/btrecord.8
/usr/local/man/man8/btreplay.8
