#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : blktrace
Version  : 1.1.0
Release  : 11
URL      : http://brick.kernel.dk/snaps/blktrace-1.1.0.tar.gz
Source0  : http://brick.kernel.dk/snaps/blktrace-1.1.0.tar.gz
Summary  : Block IO tracer
Group    : Development/Tools
License  : GPL-2.0
Requires: blktrace-bin
Requires: blktrace-doc
BuildRequires : libaio-dev
Patch1: 0001-Makefile-fix-prefix-and-manpath.patch

%description
btrace can show detailed info about what is happening on a block
device io queue. This is valuable for diagnosing and fixing
performance or application problems relating to block layer io.


Authors:
--------
    Jens Axboe <axboe@kernel.dk>

%package bin
Summary: bin components for the blktrace package.
Group: Binaries

%description bin
bin components for the blktrace package.


%package doc
Summary: doc components for the blktrace package.
Group: Documentation

%description doc
doc components for the blktrace package.


%prep
%setup -q -n blktrace-1.1.0
%patch1 -p1

%build
export LANG=C
make V=1 CFLAGS="%{optflags}" all

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/blkiomon
/usr/bin/blkparse
/usr/bin/blkrawverify
/usr/bin/blktrace
/usr/bin/bno_plot.py
/usr/bin/btrace
/usr/bin/btrecord
/usr/bin/btreplay
/usr/bin/btt
/usr/bin/iowatcher
/usr/bin/verify_blkparse

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*
